---
name: Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  tests:
    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
        django-version:
          - "2.2.17"  # first version to support Python 3.9
          - "3.1.3"  # first version to support Python 3.9
          - "3.2.0"
        include:
          - python-version: "3.8"
            django-version: "4.0.0"
          - python-version: "3.9"
            django-version: "4.0.0"
          - python-version: "3.10"
            django-version: "3.2.9"  # first version to support Python 3.10
          - python-version: "3.10"
            django-version: "4.0.0"


    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --upgrade "django~=${{ matrix.django-version}}"
      - name: Run tests
        run: python manage.py test
        working-directory: sample_project
